### ISSUE TITLE
Add more metrics, Graph visualization, and UI dashboard

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#11]
sub issues:
- [x] #269 Define UI Dashboard structure
- [x] #270 Create a force directed widget
- [x] #280 Add websockets to REST api
- [ ] #285 Integrate frontend dashboard into sbt build
- [ ] #287 Enable a topic based event bus on master
- [ ] #289 Ability to Configure Flows / DAG using NoFlo based JSON graph definition
- [ ] #422 create a ui for master informations
- [x] #433 Remove npm, bower dependencies. Generate bower dependencies dynamically.
- [ ] #434 Add api/v1.0/ prefix for all REST related calls
- [x] #449 Remove external resource
- [x] #453 Add rest service for master information
- [x] #456 Create a widget to show visjs graph
