### ISSUE TITLE
Kafka -> HBase pipeline

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#400]
We would like to see a use case where the source is kafka and a sliding window within the DAG calculates and updates an average and then writes this to hbase. 
Subtasks:
- [ ] #685 Pipeline: Fix runtime classpath and fat jar assembly to take advantage of jars on target node
- [ ] #686 Pipeline: Define all schema data using upickle
- [ ] #687 Pipeline: Create HBase tables, columns or assume they are precreated and return appropriate error info to AppMaster
- [ ] #688 Pipeline: Dynamically set zookeeper, kafka and hbase server locations in respective taskactor's prestart's
- [ ] #689 Pipeline: Possibly add CLI options to pipeline for topic, tables which would override pipeline.conf
- [ ] #690 Pipeline: Define DAG streaming behavior
- [ ] #714 Pipeline: extend KafkaConfig -> PipelineConfig
- [ ] #724 Pipeline: add data generator to pipeline example

**Comment by kkasravi** [comment]
This is what the JSON will look like coming from kafka

{
  "source_id": "ip-172-1-2-3",
  "event_id": "c4e6e427-7e45-41d8-9ba2-2223062398dc",
  "event_ts": 1417763522224,
  "metrics": [
      {
        "key": "cpu_load_5min",
        "value": 0.0029296875
      },
      {
        "key": "cpu_load_10min",
        "value": 0.0146484375
      },
      {
        "key": "cpu_load_15min",
        "value": 0.04541015625
      },
      {
        "key": "free_memory",
        "value": 3402670080
      }
  ],
  "event_number": 30
}

Wrapped in an envelope like this
{     id: [v4 uuid],     on: [UTC timestamp]     body: [inbound message content in UTF-8 encoded string] 
}

**Comment by kkasravi** [comment]
gating issues
- [ ] kafka version mismatch with CDH, 
- [ ] kafka servers
- [ ] class loading issue
- [ ] getting the right values into pipeline.conf for zookeeper, kafka (topic, etc)

**Comment by clockfly** [comment]
@kkasravi 

Please go with the upicke approach which you are comfortable of. 
Please add some UT then we can do the code merge.
