### ISSUE TITLE
Support exactly once message delivery guarantee

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#6]

**Comment by manuzhang** [comment]
- [ ] define Task interface for transaction api (#746)
- [ ] define CheckpointStore, State, Snapshot interface (#747)
- [ ] add HDFS storage support (#339)
- [ ] verify each message is processed exactly once (#748)
- [ ] add examples of using the transaction api (#749)
